name: Build Electron App

on:
  push:
    tags:
      - v*

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step_version.outputs.version }}
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}
    steps:

      - id: step_version
        run: echo "::set-output name=version::${{ steps.package_version.outputs.version }}"

      - id: step_upload_url
        run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: install dependencies
        run: npm install

      - name: Package Electron app
        run: npm run linux:electron:build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.Make_GitHub_Release.outputs.upload_url }}
          asset_path: ./dist_electron/*.AppImage
          asset_name: ${{ github.event.release.tag_name }}.AppImage
          asset_content_type: application/octet-stream