name: Publish Release

on:
    push:
      tags:
        - 'v*'

jobs:
    build_and_release:
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Set up Node.js
            uses: actions/setup-node@v2
            with:
              node-version: 18
    
          - name: install dependencies
            run: npm install
    
          - name: Package Electron app
            run: npm run electron:build
            env:
              GH_TOKEN: ${{ secrets.GH_TOKEN }}

          - name: Create a Release
            uses: "marvinpinto/action-automatic-releases@latest"
            with:
                repo_token: ${{ secrets.GH_TOKEN }}
                automatic_release_tag: "${{ github.ref_name }}-latest"
                prerelease: false
                # multiple files are separated by newlines [.exe, .dmg, .AppImage]
                files: |
                    ./dist_electron/*.AppImage
                    ./dist_electron/*.dmg
                    ./dist_electron/*.exe

          - name: Upload Release Asset Linux
            uses: actions/upload-artifact@v2
            with:
                name: Health Check Setup
                # multiple files are separated by newlines [.exe, .dmg, .AppImage]
                path: |
                    ./dist_electron/*.AppImage
                    ./dist_electron/*.dmg
                    ./dist_electron/*.exe