name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run ${{ runner.os }}:electron:build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Determine artifact filename
        id: set_artifact_filename
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            echo "::set-output name=filename::dist_electron/*.AppImage"
          elif [ "${{ runner.os }}" = "macOS" ]; then
            echo "::set-output name=filename::dist_electron/*.dmg"
          elif [ "${{ runner.os }}" = "Windows" ]; then
            echo "::set-output name=filename::dist_electron/*.exe"
          fi
        shell: bash

      - name: Create a Release and Upload Assets
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          prerelease: false
          files: ${{ steps.set_artifact_filename.outputs.filename }}

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: Health Check Setup
          path: ${{ steps.set_artifact_filename.outputs.filename }}